title: What do you eat for lunch?
description: Project and Study Homepage
author: Kwak Tae Beom
avatar: /logo.png
email: ktb5891@naver.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: Kwak Tae Beom
  card: summary
logo: logo.png
social:
  name: Kwak Tae Beom
  links:
    - https://github.com/ktb5891
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
